#include "EventManager.h"

FGenerateAudioGathered UEventManager::PlaySoundGatheredDelegate;
FOnLostXRHeadsetTracking UEventManager::LostXRHeadsetTrackingDelegate;
FOnDetectedCoinGatheredFromDirection UEventManager::CoinGatheredFromDirectionDelegate;
FOnPerformSavingPlayerInfo UEventManager::PerformSavingPlayerInfoDelegate;
FOnPerformLoadingPlayerInfo UEventManager::PerformLoadingPlayerInfoDelegate;
FOnRegainXRHeadsetTracking UEventManager::RegainXRHeadsetTrackingDelegate;
